const Register = {
	Main: {
		name: "What is your name?",
		lastname: "What is your surname?",
		phone: "Phone number",
		jobTitle: "Position",
		country: "Country",
		city: "City",
		shop: "Shop",
		email: "Email",
		password: "Password",
		confirm: "Confirm passwords",
		next: "Next",
		finish: "Finish",
		sure: "Are you sure? All data will be lost.",
		fill: "Fill in the fields",
		back: "Back",
		main: "To the main page",
		success: "Success!",
		modalMessage:
			"Thank you, your application has been accepted. Login information will be sent to your email immediately after confirmation from the administrator.",
	},
	ErrorMessage: {
		fill: "This field is required",
		title: "Please, choose job title!",
		country: "Please, choose country!",
		city: "Please, choose city!",
		shop: "Please, choose shop!",
		name: "Incorrect Name",
		lastname: "Incorrect Last Name",
		middlename: "Incorrect Middle name",
		birthday: "Invalid date",
		email: "Incorrect Email",
		phone: "Invalid phone number",
		confirm: "Please confirm your password",
		password:
			"Your password must be at least 8 characters long, include upper and lower case characters and numbers",
	},
	Placeholder: {
		name: "Name",
		lastname: "Lastname",
		middlename: "Middlename",
		birthday: "Date of Birth",
		phone: "Phone number",
		title: "Job title",
		country: "Country",
		city: "City",
		shop: "Shop",
		email: "Email",
		password: "Enter password",
		confirm: "Confirm your passwords",
		chooseCountry: "First select your country",
	},
	Title: {
		administrator: "Administrator",
		merchandiser: "Visual merchandiser",
		manager: "Store manager",
		cashier: "Cashier",
		storekeeper: "Warehouse picker",
		assistant: "Sales consultant",
		support: "Support Specialist",
		international: "International Client Relations Specialist",
	},
};

export default Register;
