const Register = {
	Main: {
		name: "Imię",
		lastname: "Nazwisko",
		phone: "Numer telefonu",
		jobTitle: "Stanowisko",
		country: "Kraj",
		city: "Miasto",
		shop: "Sklep",
		email: "Adres e-mail",
		password: "Hasło",
		confirm: "Potwierdź hasło",
		next: "Dalej",
		finish: "Skończyć",
		sure: "Na pewno? Wszystkie dane zostaną utracone.",
		fill: "Wypełnij pola",
		back: "Z powrotem",
		main: "Do strony głównej",
		success: "Powodzenie!",
		modalMessage:
			"Dziękujemy, Twoje zgłoszenie zostało przyjęte. Dane do logowania zostaną przesłane na Twój adres e-mail niezwłocznie po potwierdzeniu przez administratora.",
	},
	ErrorMessage: {
		fill: "Trzeba wypełnić pole",
		title: "Proszę wybrać stanowisko!",
		country: "Proszę wybrać kraj!",
		city: "Proszę wybrać miasto!",
		shop: "Proszę wybrać sklep!",
		name: "Nieprawidłowa nazwa",
		lastname: "Nieprawidłowe nazwisko",
		middlename: "Nieprawidłowe drugie imię",
		birthday: "Nieprawidłowa data",
		email: "Niepoprawny e-mail",
		phone: "Nieprawidłowy numer telefonu",
		confirm: "Proszę potwierdzić hasło!",
		password:
			"Twoje hasło powinno składać się z co najmniej 8 znaków, oraz zawierać welkie i małe litery i cyfry",
	},
	Placeholder: {
		name: "Imię",
		lastname: "Nazwisko",
		middlename: "Nazwisko",
		birthday: "Data urodzenia",
		phone: "Numer telefonu",
		title: "Stanowisko",
		country: "Kraj",
		city: "Miasto",
		shop: "Sklep",
		email: "Adres e-mail",
		password: "Wprowadź hasło",
		confirm: "Potwierdź hasło",
		chooseCountry: "Najpierw wybierz swój kraj",
	},
	Title: {
		administrator: "Administrator",
		merchandiser: "Visual merchandiser",
		manager: "Dyrektor sklepu",
		cashier: "Kasjer",
		storekeeper: "Magazynier - pakowacz",
		assistant: "Konsultant handlowy",
		support: "Specjalista do spraw wsparcia sprzedaży",
		international: "Specjalista do spraw relacji z międzynarodowymi klientami",
	},
};

export default Register;
